-- V1: esquema del módulo inmueble (torres y apartamentos).

CREATE TABLE torre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    numero_pisos INTEGER NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL
);

CREATE TABLE apartamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL,
    piso INTEGER NOT NULL,
    coeficiente_copropiedad NUMERIC(7,4) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    torre_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_apartamento_torre FOREIGN KEY (torre_id) REFERENCES torre(id),
    CONSTRAINT uq_apartamento_torre_numero UNIQUE (torre_id, numero)
);
