-- V2: esquema del módulo usuarios (herencia JOINED: una tabla por subclase).

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(200) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    contrasena_hash VARCHAR(255) NOT NULL,
    documento VARCHAR(50) NOT NULL,
    telefono VARCHAR(20),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMP,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_actualizacion TIMESTAMP NOT NULL
);

CREATE TABLE residente (
    id BIGINT PRIMARY KEY REFERENCES usuario(id),
    tipo_residente VARCHAR(20) NOT NULL,
    apartamento_id BIGINT NOT NULL REFERENCES apartamento(id)
);

CREATE TABLE administrador (
    id BIGINT PRIMARY KEY REFERENCES usuario(id)
);

CREATE TABLE portero (
    id BIGINT PRIMARY KEY REFERENCES usuario(id),
    turno VARCHAR(50)
);

CREATE TABLE tecnico_mantenimiento (
    id BIGINT PRIMARY KEY REFERENCES usuario(id),
    especialidad VARCHAR(100)
);
