import {
  Building2,
  CalendarRange,
  ClipboardList,
  DoorOpen,
  History,
  Home,
  Megaphone,
  MessagesSquare,
  Package,
  ShieldCheck,
  TriangleAlert,
  Truck,
  Users,
  Wallet,
  Wrench,
} from 'lucide-react'

export const roles = {
  residente: {
    key: 'residente',
    nombre: 'Residente',
    descripcion: 'Estado de cuenta, reservas, incidencias y paquetes',
    icon: Home,
    usuario: 'Juan Pérez',
    detalle: 'Torre 2 · Apto 304',
    nav: [
      { key: 'inicio', label: 'Inicio', icon: Home },
      { key: 'finanzas', label: 'Finanzas', icon: Wallet },
      { key: 'reservas', label: 'Reservas', icon: CalendarRange },
      { key: 'incidencias', label: 'Incidencias', icon: TriangleAlert },
      { key: 'paquetes', label: 'Paquetes', icon: Package },
      { key: 'comunidad', label: 'Comunidad', icon: MessagesSquare },
    ],
  },
  porteria: {
    key: 'porteria',
    nombre: 'Portería',
    descripcion: 'Registro de visitantes, paquetes y bitácora',
    icon: DoorOpen,
    usuario: 'Daniel Rojas',
    detalle: 'Turno mañana',
    nav: [
      { key: 'inicio', label: 'Inicio', icon: Home },
      { key: 'visitantes', label: 'Visitantes', icon: DoorOpen },
      { key: 'paquetes', label: 'Paquetes', icon: Truck },
      { key: 'bitacora', label: 'Bitácora', icon: ClipboardList },
    ],
  },
  mantenimiento: {
    key: 'mantenimiento',
    nombre: 'Mantenimiento',
    descripcion: 'Gestión y seguimiento de incidencias',
    icon: Wrench,
    usuario: 'Jorge Mejía',
    detalle: 'Técnico de mantenimiento',
    nav: [
      { key: 'inicio', label: 'Inicio', icon: Home },
      { key: 'incidencias', label: 'Incidencias', icon: TriangleAlert },
      { key: 'historial', label: 'Historial', icon: History },
    ],
  },
  administrador: {
    key: 'administrador',
    nombre: 'Administrador',
    descripcion: 'Supervisión general, finanzas y comunicados',
    icon: ShieldCheck,
    usuario: 'Andrea Salazar',
    detalle: 'Administración',
    nav: [
      { key: 'dashboard', label: 'Dashboard', icon: Home },
      { key: 'finanzas', label: 'Finanzas', icon: Wallet },
      { key: 'reservas', label: 'Reservas', icon: CalendarRange },
      { key: 'incidencias', label: 'Incidencias', icon: TriangleAlert },
      { key: 'comunicados', label: 'Comunicados', icon: Megaphone },
      { key: 'residentes', label: 'Residentes', icon: Users },
    ],
  },
}

export const rolCards = [
  {
    key: 'residente',
    nombre: 'Residente',
    descripcion: 'Estado de cuenta, reservas, incidencias y paquetes.',
    icon: Home,
    tint: 'bg-brand-50 text-brand-600',
  },
  {
    key: 'porteria',
    nombre: 'Portería',
    descripcion: 'Registro de visitantes, paquetes y bitácora.',
    icon: DoorOpen,
    tint: 'bg-sky-50 text-sky-600',
  },
  {
    key: 'mantenimiento',
    nombre: 'Mantenimiento',
    descripcion: 'Gestión y seguimiento de incidencias.',
    icon: Wrench,
    tint: 'bg-amber-50 text-amber-600',
  },
  {
    key: 'administrador',
    nombre: 'Administrador',
    descripcion: 'Supervisión general, finanzas y comunicados.',
    icon: Building2,
    tint: 'bg-violet-50 text-violet-600',
  },
]