spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resigest
    username: resigest
    password: resigest
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
